version: '3.1'

services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: veiculos
      MYSQL_USER: root
      MYSQL_PASSWORD: 1254
      MYSQL_ROOT_PASSWORD: 1254
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
